# These are for development and test only.
# When using imports a full path with a closing / is very important:
# __import__: /test/app_name/symmetric_encryption/

dev:
  app_name:
    symmetric_encryption:
      key:     global_key
      iv:      global_iv
      version: 1

    mysql:
      database:   secret_config_development
      username:   secret_config
      password:   secret_configrules
      host:       127.0.0.1

    mongo:
      database:   secret_config_development
      primary:    127.0.0.1:27017
      secondary:  127.0.0.1:27018

    secrets:
      secret_key_base: somereallylongstring

test:
  app_name:
    symmetric_encryption:
      key: global_key
      iv: global_iv
      version: version_1
      old:
        key: global_key
        iv: global_iv
        version: version_1

  other_application:
    symmetric_encryption:
      __import__: /test/app_name/symmetric_encryption/
      version: override_1
    database:
      __import__: /base/database/postgres/
      host: override_host
      old:
        host: override_nested_host

  other_other_application:
    symmetric_encryption:
      __import__: /test/other_application/symmetric_encryption/
      version: override_2

base:
  database:
    postgres:
      host: base_host
      port: base_port
      username: base_user_1
      old:
        host: base_host
        port: base_port
        username: base_user_2

