# These are for development and test only.
dev:
  app_name:
    symmetric_encryption:
      key:     global_key
      iv:      global_iv
      version: 1

    mysql:
      database:   secret_config_development
      username:   secret_config
      password:   secret_configrules
      host:       127.0.0.1

    mongo:
      database:   secret_config_development
      primary:    127.0.0.1:27017
      secondary:  127.0.0.1:27018

    secrets:
      secret_key_base: somereallylongstring

test:
  app_name:
    symmetric_encryption:
      key: global_key
      iv: global_iv
      version: version_1

  other_application:
   symmetric_encryption:
     __import__: /test/app_name/symmetric_encryption
     version: override_1

  other_other_application:
    symmetric_encryption:
      __import__: /test/other_application/symmetric_encryption
      version: override_2
